#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/TB-X505X

PRODUCT_COPY_FILES += \
    vendor/lenovo/TB-X505X/proprietary/product/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_PRODUCT)/etc/dpm/dpm.conf \
    vendor/lenovo/TB-X505X/proprietary/product/etc/init/dpmd.rc:$(TARGET_COPY_OUT_PRODUCT)/etc/init/dpmd.rc \
    vendor/lenovo/TB-X505X/proprietary/system/etc/cne/Nexus/ATT/ATT_profiles.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/Nexus/ATT/ATT_profiles.xml \
    vendor/lenovo/TB-X505X/proprietary/system/etc/cne/Nexus/ROW/ROW_profiles.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/Nexus/ROW/ROW_profiles.xml \
    vendor/lenovo/TB-X505X/proprietary/system/etc/cne/Nexus/VZW/VZW_profiles.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/cne/Nexus/VZW/VZW_profiles.xml \
    vendor/lenovo/TB-X505X/proprietary/system/etc/init/wfdservice.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/wfdservice.rc \
    vendor/lenovo/TB-X505X/proprietary/system/etc/perf/wlc_model.tflite:$(TARGET_COPY_OUT_SYSTEM)/etc/perf/wlc_model.tflite \
    vendor/lenovo/TB-X505X/proprietary/system/etc/powerhint.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/powerhint.xml \
    vendor/lenovo/TB-X505X/proprietary/system/etc/wfdconfig.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/wfdconfig.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/Diag.cfg:$(TARGET_COPY_OUT_VENDOR)/Diag.cfg \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/Diag.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/Diag.cfg \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/IPACM_cfg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/IPACM_cfg.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/a2dp_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/a2dp_audio_policy_configuration.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/MTP_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_workspaceFile.qwsp \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Bluetooth_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_General_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Global_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Handset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Hdmi_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Headset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_Speaker_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/msm8952-tasha-snd-card/MTP_WCD9335_workspaceFile.qwsp \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Bluetooth_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_General_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Global_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Handset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Hdmi_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Headset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8917-tmo-snd-card/QRD_TMO_Speaker_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Bluetooth_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_General_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Global_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Handset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Hdmi_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Headset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8940-sku6-snd-card/QRD_SKU6_Speaker_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Bluetooth_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_General_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Global_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Handset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Hdmi_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Headset_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/msm8952-sku2-snd-card/QRD_SKU2_Speaker_cal.acdb \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio/audio_policy_configuration.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_effects.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_output_policy.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_output_policy.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_platform_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_platform_info_extcodec.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_platform_info_extcodec.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_policy.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/audio_tuning_mixer.txt:$(TARGET_COPY_OUT_VENDOR)/etc/audio_tuning_mixer.txt \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/gc5035_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/gc5035_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/lenove_sp2509_lcetron_front_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lenove_sp2509_lcetron_front_i_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/lenovo_gc02m1_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lenovo_gc02m1_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/lenovo_gc2375h_ui_front_ii_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lenovo_gc2375h_ui_front_ii_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/lenovo_gc5025a_holitech_back_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lenovo_gc5025a_holitech_back_i_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/lenovo_hi556_lcetron_anatech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lenovo_hi556_lcetron_anatech_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/lenovo_hi556_lcetron_back_i_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lenovo_hi556_lcetron_back_i_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/camera/lenovo_s5k4h7_ofilm_i_p400_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/lenovo_s5k4h7_ofilm_i_p400_chromatix.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/flp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/fstab.qcom:$(TARGET_COPY_OUT_VENDOR)/etc/fstab.qcom \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/ftm_test_config:$(TARGET_COPY_OUT_VENDOR)/etc/ftm_test_config \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/ftm_test_config_wcd9335:$(TARGET_COPY_OUT_VENDOR)/etc/ftm_test_config_wcd9335 \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/hbtpcfg.dat:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/hbtpcfg.dat \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/hbtpcfg2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/hbtpcfg2.dat \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/hbtpcfg_8917.dat:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/hbtpcfg_8917.dat \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/hbtpcfg_adsp_800s_fhd.dat:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/hbtpcfg_adsp_800s_fhd.dat \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/hbtpcfg_msm8937_800s_fhd.dat:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/hbtpcfg_msm8937_800s_fhd.dat \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/hbtpcfg_sdm450_801s_fhdp.dat:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/hbtpcfg_sdm450_801s_fhdp.dat \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/loader.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/loader.cfg \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/qtc800h.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800h.bin \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/qtc800s_dsp.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc800s_dsp.bin \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/hbtp/qtc801s_450.bin:$(TARGET_COPY_OUT_VENDOR)/etc/hbtp/qtc801s_450.bin \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.atrace@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.atrace@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.audio@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.audio@2.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.camera.provider@2.4-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.camera.provider@2.4-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.cas@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.cas@1.1-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.configstore@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.configstore@1.1-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.drm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.drm@1.2-service.clearkey.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.2-service.clearkey.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.drm@1.2-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.2-service.widevine.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.gnss@2.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.0-service-qti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.graphics.allocator@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@2.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.graphics.composer@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.composer@2.1-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.health@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.health@2.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.light@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.light@2.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.media.omx@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.omx@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.memtrack@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.memtrack@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.power@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.power@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.sensors@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.thermal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.vibrator@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.vibrator@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/android.hardware.wifi@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.qualcomm.qti.wifidisplayhal@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/hostapd.android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hostapd.android.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/init.qdmastats.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qdmastats.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/init.qti.fm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.fm.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/ipacm-diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm-diag.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/ipacm.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/rild.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.fingerprint.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.fingerprint.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.acc_calibrate@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.acc_calibrate@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.cryptfshw@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.cryptfshw@1.0-service-qti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.factory@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.factory@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.fstman@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.fstman@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.perf@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.perf@2.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qdutils_disp@1.0-service-qti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.hardware.wigig.supptunnel@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.wigig.supptunnel@1.0-service.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vendor.rild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.rild.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/init/vndservicemanager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vndservicemanager.rc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/lct_loopback_config_file:$(TARGET_COPY_OUT_VENDOR)/etc/lct_loopback_config_file \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/lm/AdaptLaunchFeature.xml:$(TARGET_COPY_OUT_VENDOR)/etc/lm/AdaptLaunchFeature.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_8937_v1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_8937_v1.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_8956.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_8956.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_google_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_audio.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_google_telephony.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_telephony.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_google_video.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_video.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_google_video_le.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_video_le.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_vendor.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_codecs_vendor_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_vendor_audio.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_profiles_8956.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_8956.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/media_profiles_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_vendor.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_mtp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_mtp.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_qrd_sku1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_qrd_sku1.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_qrd_sku2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_qrd_sku2.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_qrd_skuh.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_qrd_skuh.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_qrd_skuhf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_qrd_skuhf.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_qrd_skui.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_qrd_skui.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_qrd_skum.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_qrd_skum.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_qrd_skun.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_qrd_skun.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_sdm439_pm8953.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_sdm439_pm8953.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_skuk.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_skuk.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_wcd9306.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_wcd9306.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_wcd9326.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_wcd9326.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_wcd9330.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_wcd9330.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mixer_paths_wcd9335.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths_wcd9335.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/mkshrc:$(TARGET_COPY_OUT_VENDOR)/etc/mkshrc \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/msm_irqbalance.conf:$(TARGET_COPY_OUT_VENDOR)/etc/msm_irqbalance.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/perf/commonresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/commonresourceconfigs.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/perf/perf-profile0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile0.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/perf/perf-profile1.conf:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perf-profile1.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/perf/perfboostsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfboostsconfig.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/perf/perfconfigstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/perfconfigstore.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/perf/targetconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetconfig.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/perf/targetresourceconfigs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/perf/targetresourceconfigs.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/qdcm_calib_data_boe_icnl9706_800p_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_boe_icnl9706_800p_video_mode_dsi_panel.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/qdcm_calib_data_inx_jd9365_800p_video_mode_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_inx_jd9365_800p_video_mode_dsi_panel.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/r_submix_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/r_submix_audio_policy_configuration.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/seccomp_policy/configstore@1.1.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/configstore@1.1.policy \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sound_trigger_mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sound_trigger_mixer_paths_wcd9306.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths_wcd9306.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sound_trigger_mixer_paths_wcd9330.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths_wcd9330.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sound_trigger_mixer_paths_wcd9335.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_mixer_paths_wcd9335.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/sound_trigger_platform_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sound_trigger_platform_info.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_policy_configuration.xml \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/WCNSS_qcom_cfg.ini \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/aoa_cldb_falcon.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_falcon.bin \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/aoa_cldb_swl14.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/aoa_cldb_swl14.bin \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/fstman.ini:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/fstman.ini \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/wigig_p2p_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wigig_p2p_supplicant.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/wigig_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wigig_supplicant.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/lenovo/TB-X505X/proprietary/vendor/etc/xtwifi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/AbovCapSense.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense.BIN \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a506_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b00 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a506_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b01 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a506_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.b02 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a506_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.elf \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a506_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a506_zap.mdt \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/lenovo/TB-X505X/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    vendor/lenovo/TB-X505X/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    vendor/lenovo/TB-X505X/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    vendor/lenovo/TB-X505X/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    vendor/lenovo/TB-X505X/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    vendor/lenovo/TB-X505X/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    vendor/lenovo/TB-X505X/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    vendor/lenovo/TB-X505X/proprietary/vendor/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/ueventd.rc

PRODUCT_PACKAGES += \
    libGLES_android \
    vendor.qti.hardware.sigma_miracast@1.0-impl \
    libFileMux \
    libOmxMux \
    libdisplayconfig \
    libmiracastsystem \
    libmmosal \
    libmmparser_lite \
    libmmrtpdecoder \
    libmmrtpencoder \
    libqdMetaData.system \
    libstagefright_bufferpool@2.0.1 \
    libstagefright_codecbase \
    libwfdclient \
    vendor.qti.hardware.sigma_miracast@1.0-halimpl \
    libaacwrapper \
    libwfdavenhancements \
    libwfdcodecv4l2 \
    libwfdcommonutils \
    libwfdconfigutils \
    libwfdmminterface \
    libwfdmmsink \
    libwfdmmsrc \
    libwfdrtsp \
    libwfdservice \
    libwfdsm \
    libwfduibcinterface \
    libwfduibcsink \
    libwfduibcsinkinterface \
    libwfduibcsrc \
    libwfduibcsrcinterface \
    btaudio_offload_if \
    camera.device@1.0-impl \
    camera.device@3.2-impl \
    camera.device@3.3-impl \
    camera.device@3.4-external-impl \
    camera.device@3.4-impl \
    camera.device@3.5-external-impl \
    camera.device@3.5-impl \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.bluetooth_audio@1.0 \
    com.qualcomm.qti.dpm.api@1.0 \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    ftm_fm_lib \
    activity_recognition.msm8937 \
    android.hardware.audio.effect@2.0-impl \
    android.hardware.audio.effect@4.0-impl \
    android.hardware.audio.effect@5.0-impl \
    android.hardware.audio@2.0-impl \
    android.hardware.audio@4.0-impl \
    android.hardware.audio@5.0-impl \
    android.hardware.bluetooth.audio@2.0-impl \
    android.hardware.camera.provider@2.4-impl \
    android.hardware.drm@1.0-impl \
    android.hardware.graphics.allocator@2.0-impl \
    android.hardware.graphics.composer@2.1-impl \
    android.hardware.light@2.0-impl \
    android.hardware.memtrack@1.0-impl \
    android.hardware.power@1.0-impl \
    android.hardware.renderscript@1.0-impl \
    android.hardware.sensors@1.0-impl \
    android.hardware.thermal@1.0-impl \
    android.hardware.vibrator@1.0-impl \
    audio.bluetooth.default \
    audio.bluetooth_qti.default \
    audio.primary.default \
    audio.primary.msm8937 \
    audio.r_submix.default \
    audio.usb.default \
    com.qualcomm.qti.ant@1.0-impl \
    gatekeeper.msm8937 \
    gralloc.default \
    gralloc.msm8937 \
    hwcomposer.msm8937 \
    keystore.msm8937 \
    lights.msm8937 \
    local_time.default \
    memtrack.msm8937 \
    power.default \
    power.qcom \
    sensors.msm8937_64 \
    sound_trigger.primary.msm8937 \
    thermal.msm8937 \
    vendor.qti.esepowermanager@1.0-impl \
    vendor.qti.gnss@3.0-impl \
    vendor.qti.hardware.acc_calibrate@1.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.0-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.fm@1.0-impl \
    vendor.qti.hardware.iop@2.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    vibrator.default \
    vulkan.msm8937 \
    lib-imsSDP \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsvtcore \
    lib-imsxml \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libAlacSwDec \
    libApeSwDec \
    libC2D2 \
    libCB \
    libEGL_adreno \
    libFlacSwDec \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libI420colorconvert \
    libMpeg4SwEncoder \
    libOmxAacDec \
    libOmxAacEnc \
    libOmxAlacDec \
    libOmxAlacDecSw \
    libOmxAmrDec \
    libOmxAmrEnc \
    libOmxAmrwbplusDec \
    libOmxApeDec \
    libOmxApeDecSw \
    libOmxCore \
    libOmxEvrcDec \
    libOmxEvrcEnc \
    libOmxG711Dec \
    libOmxG711Enc \
    libOmxQcelp13Dec \
    libOmxQcelp13Enc \
    libOmxSwVdec \
    libOmxSwVencMpeg4 \
    libOmxVdec \
    libOmxVenc \
    libOmxVpp \
    libOmxWmaDec \
    libOpenCL \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libRSDriver_adreno \
    libSecureUILib \
    libStDrvInt \
    libSubSystemShutdown \
    libUBWC \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libalsautils \
    libaoa \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioconfigstore \
    libaudioparsers \
    libbase64 \
    libbatching \
    libbccQTI \
    libbluetooth_audio_session \
    libbluetooth_audio_session_qti \
    libbt-hidlclient \
    libbthost_if \
    libbtnv \
    libc2d30-a3xx \
    libc2d30_bltlib \
    libc2dcolorconvert \
    libcacertclient \
    libcamera2ndk_vendor \
    libcapiv2svacnn \
    libcapiv2vop \
    libcdsp_default_listener \
    libcdsprpc \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libconfigdb \
    libcpion \
    libcryptfshwcommon \
    libcryptfshwhidl \
    libdapparamstorage \
    libdataitems \
    libdiag \
    libdiagjni \
    libdisp-aba \
    libdpmqmihal \
    libdrmfs \
    libdrmtime \
    libdrmutils \
    libdsi_netctrl \
    libdsutils \
    libfastcrc \
    libfastcvadsp_stub \
    libfastcvopt \
    libfastrpc_utf_stub \
    libgarden \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpu_tonemapper \
    libgrallocutils \
    libgsl \
    libhbtpclient \
    libhbtpdsp \
    libhbtpfrmwk \
    libhdcpsrm \
    libhdr_tm \
    libhwc2onfbadapter \
    libhypv_intercept \
    libidl \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libjson \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    liblistenjni \
    liblistensoundmodel2 \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_core \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    liblqe \
    libmdmdetect \
    libmdsprpc \
    libminksocket \
    libmiracast \
    libmm-color-convertor \
    libmm-hdcpmgr \
    libmm-omxcore \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmosal_proprietary \
    libmulawdec \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    liboemaids_vendor \
    libpdmapper \
    libpdnotifier \
    libperfconfig \
    libperfgluelayer \
    libperipheral_client \
    libpvr \
    libq3dtools_adreno \
    libqcbor \
    libqcci_legacy \
    libqcmaputils \
    libqcrilFramework \
    libqcrildatactl \
    libqdMetaData \
    libqdi \
    libqdma \
    libqdma_file_agent \
    libqdp \
    libqdutils \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqrtr \
    libqsap_sdk \
    libqservice \
    libqsocket \
    libqti-iopd-client \
    libqti-perfd-client \
    libqti-perfd \
    libqti-util \
    libqti-utils \
    libqti_vndfwk_detect \
    libqtigef \
    libqtikeymaster4 \
    librcc \
    librecovery_updater_msm \
    libril-qc-hal-qmi \
    libril-qc-ltedirectdisc \
    libril-qc-qmi-1 \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librmnetctl \
    librmp \
    librpmb \
    librs_adreno \
    librs_adreno_sha1 \
    libscalar \
    libscveBlobDescriptor \
    libscveBlobDescriptor_stub \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libscvePanorama \
    libscvePanorama_lite \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsecureui \
    libsecureui_svcsock \
    libseemore \
    libsensor1 \
    libsensor_reg \
    libsettings \
    libsi \
    libskewknob \
    libslimclient \
    libssc_default_listener \
    libssd \
    libstagefright_soft_qtiflacdec \
    libstagefrightdolby \
    libstagefrighthw \
    libstreamparser \
    libsubsystem_control \
    libswvdec \
    libsynergy_loc_api \
    libsysmon_cdsp_skel \
    libsystem_health_mon \
    libthermalclient \
    libtime_genoff \
    libtinycompress_vendor \
    libtinyxml \
    libtinyxml2_1 \
    libtzdrmgenprov \
    libvideoutils \
    libvndfwk_detect_jni.qti \
    libvpplibrary \
    libwfdhdcpcp \
    libwifi-hal-ctrl \
    libwifi-hal-qcom \
    libwms \
    libwpa_client \
    libwqe \
    libxml \
    libxtadapter \
    libclearkeycasplugin \
    libdrmclearkeyplugin \
    libwvdrmengine \
    qcrild_librilutils \
    qtibus \
    qtimutex \
    sensor_calibrate \
    sensors.ssc \
    libasphere \
    libdynproc \
    libqcbassboost \
    libqcompostprocbundle \
    libqcomvisualizer \
    libqcomvoiceprocessing \
    libqcreverb \
    libqcvirt \
    libswdap \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.config@1.0 \
    vendor.display.config@1.1 \
    vendor.display.config@1.2 \
    vendor.display.config@1.3 \
    vendor.display.config@1.4 \
    vendor.display.config@1.5 \
    vendor.display.config@1.6 \
    vendor.display.config@1.7 \
    vendor.display.config@1.8 \
    vendor.display.config@1.9 \
    vendor.display.postproc@1.0 \
    vendor.dolby.hardware.dms@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0-service \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.acc_calibrate@1.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_audio@2.0 \
    vendor.qti.hardware.bluetooth_dun@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.btconfigstore@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.camera.device@1.0 \
    vendor.qti.hardware.capabilityconfigstore@1.0 \
    vendor.qti.hardware.cryptfshw@1.0 \
    vendor.qti.hardware.cvp@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.improvetouch.touchcompanion@1.0-service \
    vendor.qti.hardware.improvetouch.touchcompanion@1.0 \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.perf@1.0 \
    vendor.qti.hardware.perf@2.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0 \
    vendor.qti.hardware.sigma_miracast@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.wigig.netperftuner@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.imsrtpservice@2.0 \
    vendor.qti.imsrtpservice@2.1-service-Impl \
    vendor.qti.imsrtpservice@2.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.power.pasrmanager@1.0 \
    vendor.qti.voiceprint@1.0 \
    com.qualcomm.qti.wifidisplayhal@1.0-halimpl \
    com.qualcomm.qti.wifidisplayhal@1.0 \
    android.hardware.soundtrigger@2.1-impl \
    camera.msm8937 \
    libOmxDsdDec \
    libOmxVideoDSMode \
    libactuator_ad5816g \
    libactuator_ad5823 \
    libactuator_ak7345 \
    libactuator_ak7371 \
    libactuator_bu64244gwz \
    libactuator_bu64297 \
    libactuator_dw9714 \
    libactuator_dw9714_anatech \
    libactuator_dw9714_gc5035 \
    libactuator_dw9716 \
    libactuator_dw9761b \
    libactuator_dw9763 \
    libactuator_dw9763b \
    libactuator_dw9790a \
    libactuator_dw9800 \
    libactuator_gt9768_ofilm \
    libactuator_gt9772 \
    libactuator_lc898122 \
    libactuator_lc898212xd \
    libactuator_lc898212xd_qc2002 \
    libactuator_lc898217xc \
    libactuator_pseudo \
    libactuator_rohm_bu64243gwz \
    libadm \
    libadpcmdec \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_gc5035_common \
    libchromatix_gc5035_cpp_liveshot \
    libchromatix_gc5035_cpp_preview \
    libchromatix_gc5035_cpp_snapshot \
    libchromatix_gc5035_cpp_video \
    libchromatix_gc5035_default_preview_3a \
    libchromatix_gc5035_default_video \
    libchromatix_gc5035_default_video_3a \
    libchromatix_gc5035_postproc \
    libchromatix_gc5035_preview \
    libchromatix_gc5035_snapshot \
    libchromatix_gc5035_zsl_preview \
    libchromatix_gc5035_zsl_video \
    libchromatix_lenove_sp2509_lcetron_front_i_a3_default_preview \
    libchromatix_lenove_sp2509_lcetron_front_i_a3_default_video \
    libchromatix_lenove_sp2509_lcetron_front_i_a3_hfr_120 \
    libchromatix_lenove_sp2509_lcetron_front_i_a3_hfr_60 \
    libchromatix_lenove_sp2509_lcetron_front_i_a3_hfr_90 \
    libchromatix_lenove_sp2509_lcetron_front_i_common \
    libchromatix_lenove_sp2509_lcetron_front_i_common_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_ds_chromatix \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_hfr_120 \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_hfr_60 \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_hfr_90 \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_liveshot \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_liveshot_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_preview \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_preview_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_snapshot \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_snapshot_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_us_chromatix \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_video \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_video_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_cpp_video_full \
    libchromatix_lenove_sp2509_lcetron_front_i_default_video \
    libchromatix_lenove_sp2509_lcetron_front_i_default_video_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_hfr_120 \
    libchromatix_lenove_sp2509_lcetron_front_i_hfr_60 \
    libchromatix_lenove_sp2509_lcetron_front_i_hfr_90 \
    libchromatix_lenove_sp2509_lcetron_front_i_liveshot \
    libchromatix_lenove_sp2509_lcetron_front_i_postproc \
    libchromatix_lenove_sp2509_lcetron_front_i_postproc_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_preview \
    libchromatix_lenove_sp2509_lcetron_front_i_snapshot \
    libchromatix_lenove_sp2509_lcetron_front_i_snapshot_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_video_full \
    libchromatix_lenove_sp2509_lcetron_front_i_zsl_preview \
    libchromatix_lenove_sp2509_lcetron_front_i_zsl_preview_cts \
    libchromatix_lenove_sp2509_lcetron_front_i_zsl_video \
    libchromatix_lenove_sp2509_lcetron_front_i_zsl_video_cts \
    libchromatix_lenovo_gc02m1_a3_default_preview \
    libchromatix_lenovo_gc02m1_a3_default_video \
    libchromatix_lenovo_gc02m1_a3_hfr_120 \
    libchromatix_lenovo_gc02m1_a3_hfr_60 \
    libchromatix_lenovo_gc02m1_a3_hfr_90 \
    libchromatix_lenovo_gc02m1_common \
    libchromatix_lenovo_gc02m1_cpp_ds_chromatix \
    libchromatix_lenovo_gc02m1_cpp_hfr_120 \
    libchromatix_lenovo_gc02m1_cpp_hfr_60 \
    libchromatix_lenovo_gc02m1_cpp_hfr_90 \
    libchromatix_lenovo_gc02m1_cpp_liveshot \
    libchromatix_lenovo_gc02m1_cpp_preview \
    libchromatix_lenovo_gc02m1_cpp_snapshot \
    libchromatix_lenovo_gc02m1_cpp_us_chromatix \
    libchromatix_lenovo_gc02m1_cpp_video \
    libchromatix_lenovo_gc02m1_cpp_video_full \
    libchromatix_lenovo_gc02m1_default_video \
    libchromatix_lenovo_gc02m1_hfr_120 \
    libchromatix_lenovo_gc02m1_hfr_60 \
    libchromatix_lenovo_gc02m1_hfr_90 \
    libchromatix_lenovo_gc02m1_liveshot \
    libchromatix_lenovo_gc02m1_postproc \
    libchromatix_lenovo_gc02m1_preview \
    libchromatix_lenovo_gc02m1_snapshot \
    libchromatix_lenovo_gc02m1_video_full \
    libchromatix_lenovo_gc02m1_zsl_preview \
    libchromatix_lenovo_gc02m1_zsl_video \
    libchromatix_lenovo_gc2375h_ui_front_ii_a3_default_preview \
    libchromatix_lenovo_gc2375h_ui_front_ii_a3_default_video \
    libchromatix_lenovo_gc2375h_ui_front_ii_a3_hfr_120 \
    libchromatix_lenovo_gc2375h_ui_front_ii_a3_hfr_60 \
    libchromatix_lenovo_gc2375h_ui_front_ii_a3_hfr_90 \
    libchromatix_lenovo_gc2375h_ui_front_ii_common \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_ds_chromatix \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_hfr_120 \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_hfr_60 \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_hfr_90 \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_liveshot \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_preview \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_snapshot \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_us_chromatix \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_video \
    libchromatix_lenovo_gc2375h_ui_front_ii_cpp_video_full \
    libchromatix_lenovo_gc2375h_ui_front_ii_default_video \
    libchromatix_lenovo_gc2375h_ui_front_ii_hfr_120 \
    libchromatix_lenovo_gc2375h_ui_front_ii_hfr_60 \
    libchromatix_lenovo_gc2375h_ui_front_ii_hfr_90 \
    libchromatix_lenovo_gc2375h_ui_front_ii_liveshot \
    libchromatix_lenovo_gc2375h_ui_front_ii_postproc \
    libchromatix_lenovo_gc2375h_ui_front_ii_preview \
    libchromatix_lenovo_gc2375h_ui_front_ii_snapshot \
    libchromatix_lenovo_gc2375h_ui_front_ii_video_full \
    libchromatix_lenovo_gc2375h_ui_front_ii_zsl_preview \
    libchromatix_lenovo_gc2375h_ui_front_ii_zsl_video \
    libchromatix_lenovo_gc5025a_holitech_back_i_a3_default_preview \
    libchromatix_lenovo_gc5025a_holitech_back_i_a3_default_video \
    libchromatix_lenovo_gc5025a_holitech_back_i_a3_hfr_120 \
    libchromatix_lenovo_gc5025a_holitech_back_i_a3_hfr_60 \
    libchromatix_lenovo_gc5025a_holitech_back_i_a3_hfr_90 \
    libchromatix_lenovo_gc5025a_holitech_back_i_common \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_ds_chromatix \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_hfr_120 \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_hfr_60 \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_hfr_90 \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_liveshot \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_preview \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_snapshot \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_us_chromatix \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_video \
    libchromatix_lenovo_gc5025a_holitech_back_i_cpp_video_full \
    libchromatix_lenovo_gc5025a_holitech_back_i_default_video \
    libchromatix_lenovo_gc5025a_holitech_back_i_hfr_120 \
    libchromatix_lenovo_gc5025a_holitech_back_i_hfr_60 \
    libchromatix_lenovo_gc5025a_holitech_back_i_hfr_90 \
    libchromatix_lenovo_gc5025a_holitech_back_i_liveshot \
    libchromatix_lenovo_gc5025a_holitech_back_i_postproc \
    libchromatix_lenovo_gc5025a_holitech_back_i_preview \
    libchromatix_lenovo_gc5025a_holitech_back_i_snapshot \
    libchromatix_lenovo_gc5025a_holitech_back_i_video_full \
    libchromatix_lenovo_gc5025a_holitech_back_i_zsl_preview \
    libchromatix_lenovo_gc5025a_holitech_back_i_zsl_video \
    libchromatix_lenovo_hi556_lcetron_anatech_a3_default_preview \
    libchromatix_lenovo_hi556_lcetron_anatech_a3_default_video \
    libchromatix_lenovo_hi556_lcetron_anatech_a3_hfr_120 \
    libchromatix_lenovo_hi556_lcetron_anatech_a3_hfr_60 \
    libchromatix_lenovo_hi556_lcetron_anatech_a3_hfr_90 \
    libchromatix_lenovo_hi556_lcetron_anatech_common \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_ds_chromatix \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_hfr_120 \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_hfr_60 \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_hfr_90 \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_liveshot \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_preview \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_snapshot \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_us_chromatix \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_video \
    libchromatix_lenovo_hi556_lcetron_anatech_cpp_video_full \
    libchromatix_lenovo_hi556_lcetron_anatech_default_video \
    libchromatix_lenovo_hi556_lcetron_anatech_hfr_120 \
    libchromatix_lenovo_hi556_lcetron_anatech_hfr_60 \
    libchromatix_lenovo_hi556_lcetron_anatech_hfr_90 \
    libchromatix_lenovo_hi556_lcetron_anatech_liveshot \
    libchromatix_lenovo_hi556_lcetron_anatech_postproc \
    libchromatix_lenovo_hi556_lcetron_anatech_preview \
    libchromatix_lenovo_hi556_lcetron_anatech_snapshot \
    libchromatix_lenovo_hi556_lcetron_anatech_video_full \
    libchromatix_lenovo_hi556_lcetron_anatech_zsl_preview \
    libchromatix_lenovo_hi556_lcetron_anatech_zsl_video \
    libchromatix_lenovo_hi556_lcetron_back_i_a3_default_preview \
    libchromatix_lenovo_hi556_lcetron_back_i_a3_default_preview_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_a3_default_video \
    libchromatix_lenovo_hi556_lcetron_back_i_a3_default_video_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_a3_hfr_120 \
    libchromatix_lenovo_hi556_lcetron_back_i_a3_hfr_60 \
    libchromatix_lenovo_hi556_lcetron_back_i_a3_hfr_90 \
    libchromatix_lenovo_hi556_lcetron_back_i_common \
    libchromatix_lenovo_hi556_lcetron_back_i_common_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_ds_chromatix \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_hfr_120 \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_hfr_60 \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_hfr_90 \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_liveshot \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_liveshot_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_preview \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_preview_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_snapshot \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_snapshot_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_us_chromatix \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_video \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_video_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_cpp_video_full \
    libchromatix_lenovo_hi556_lcetron_back_i_default_video \
    libchromatix_lenovo_hi556_lcetron_back_i_default_video_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_hfr_120 \
    libchromatix_lenovo_hi556_lcetron_back_i_hfr_60 \
    libchromatix_lenovo_hi556_lcetron_back_i_hfr_90 \
    libchromatix_lenovo_hi556_lcetron_back_i_liveshot \
    libchromatix_lenovo_hi556_lcetron_back_i_postproc \
    libchromatix_lenovo_hi556_lcetron_back_i_postproc_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_preview \
    libchromatix_lenovo_hi556_lcetron_back_i_preview_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_snapshot \
    libchromatix_lenovo_hi556_lcetron_back_i_snapshot_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_video_full \
    libchromatix_lenovo_hi556_lcetron_back_i_zsl_preview \
    libchromatix_lenovo_hi556_lcetron_back_i_zsl_preview_cts \
    libchromatix_lenovo_hi556_lcetron_back_i_zsl_video \
    libchromatix_lenovo_hi556_lcetron_back_i_zsl_video_cts \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_a3_zsl_preview \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_a3_zsl_video \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_common \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cpp_liveshot \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cpp_preview \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cpp_snapshot \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cpp_snapshot_hdr \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cpp_video \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_a3_zsl_preview \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_a3_zsl_video \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_common \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_cpp_liveshot \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_cpp_preview \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_cpp_snapshot \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_cpp_video \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_default_preview_3a \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_default_video \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_default_video_3a \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_postproc \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_preview \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_cts_snapshot \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_default_preview_3a \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_default_video \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_default_video_3a \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_hdr_preview_3a \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_postproc \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_preview \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_snapshot \
    libchromatix_lenovo_s5k4h7_ofilm_i_p400_snapshot_hdr \
    libcppf \
    libdepthmapwrapper \
    libdrc \
    libdsd2pcm \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_atmel_at24c32e_eeprom \
    libmmcamera_bokeh \
    libmmcamera_csidtg \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_dw9761b_2d_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_imx214 \
    libmmcamera_imx230 \
    libmmcamera_imx258 \
    libmmcamera_imx258_gt24c16_eeprom \
    libmmcamera_imx258_gt24c32_eeprom \
    libmmcamera_imx258_mono \
    libmmcamera_imx258_mono_gt24c32_eeprom \
    libmmcamera_imx318 \
    libmmcamera_imx362 \
    libmmcamera_imx362_gt24c64a \
    libmmcamera_imx376 \
    libmmcamera_interface \
    libmmcamera_irs1645 \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_le2464c_eeprom \
    libmmcamera_le2464c_master_eeprom \
    libmmcamera_lenovo_gc02m1 \
    libmmcamera_lenovo_gc2375h_ui_front_ii \
    libmmcamera_lenovo_gc5025a_holitech_back_i \
    libmmcamera_lenovo_gc5025a_holitech_back_i_eeprom \
    libmmcamera_lenovo_gc5035 \
    libmmcamera_lenovo_gc5035_eeprom \
    libmmcamera_lenovo_hi556_lcetron_anatech \
    libmmcamera_lenovo_hi556_lcetron_back_i \
    libmmcamera_lenovo_hi556_lcetron_back_i_eeprom \
    libmmcamera_lenovo_s5k4h7_ofilm_i_eeprom \
    libmmcamera_lenovo_s5k4h7_ofilm_i_p400 \
    libmmcamera_lenovo_sp2509h_lcetron_front_i \
    libmmcamera_m24c64s_eeprom \
    libmmcamera_onsemi_cat24c16_eeprom \
    libmmcamera_onsemi_cat24c32_eeprom \
    libmmcamera_onsemi_cat24c32_imx362_eeprom \
    libmmcamera_ov13850_q13v06k \
    libmmcamera_ov2685 \
    libmmcamera_ov2685_scv3b4035 \
    libmmcamera_ov4188 \
    libmmcamera_ov4688 \
    libmmcamera_ov4688_eeprom \
    libmmcamera_ov5670 \
    libmmcamera_ov7251 \
    libmmcamera_ov8856 \
    libmmcamera_ov8856_2lane \
    libmmcamera_ov8856_4lane \
    libmmcamera_ov8865 \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_qtech_f3l8yam_eeprom \
    libmmcamera_qtech_f5670bq_eeprom \
    libmmcamera_quadracfa \
    libmmcamera_rohm_brcg064gwz_3_eeprom \
    libmmcamera_s5k3m2xm \
    libmmcamera_s5k3m2xx \
    libmmcamera_s5k3m3sm \
    libmmcamera_s5k3p3sm \
    libmmcamera_sony_imx214_eeprom \
    libmmcamera_sony_imx298_eeprom \
    libmmcamera_sony_imx378_eeprom \
    libmmcamera_stillmore_lib \
    libmmcamera_sunny_8865_eeprom \
    libmmcamera_sunny_gt24c64a_imx362_eeprom \
    libmmcamera_sunny_gt24c64a_imx376_eeprom \
    libmmcamera_sunny_q13v06k_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_truly_cma481_eeprom \
    libmmcamera_truly_cmb433_eeprom \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libsmwrapper \
    libstagefright_soft_ddpdec \
    libstagefright_softomx_plugin \
    libsurround_3mic_proc \
    libvpx \
    libvqzip \
    libwfdcommonutils_proprietary \
    libwfdhaldsmanager \
    libwfdmmservice \
    libwfdmodulehdcpsession \
    libadaptlaunch \
    libappclassifier \
    libcert_parse.wpa_s \
    libdlbdsservice \
    libgameoptfeature \
    libgarden_haltests_e2e \
    libhwminijail \
    libipanat \
    libkeystore-engine-wifi-hidl \
    libkeystore-wifi-hidl \
    liblearningmodule \
    libmeters-ns \
    libmeters \
    libnetfilter_conntrack \
    libnfnetlink \
    liboffloadhal \
    libreffeature \
    libsensorndkbridge \
    libwifi-hal \
    libwvhidl \
    vendor.dolby.hardware.dms@1.0-impl \
    vendor.qti.hardware.factory@1.0 \
    vendor.qti.hardware.factory@1.1 \
    vendor.qti.hardware.fstman@1.0 \
    vendor.qti.hardware.wifi.hostapd@1.0 \
    vendor.qti.hardware.wifi.hostapd@1.1 \
    vendor.qti.hardware.wifi.keystore@1.0 \
    vendor.qti.hardware.wifi.supplicant@2.0 \
    vendor.qti.hardware.wifi.supplicant@2.1 \
    vendor.qti.hardware.wigig.supptunnel@1.0 \
    vendor_lib_rfsa_adsp_libFastRPC_AUE_Forward_skel_so \
    vendor_lib_rfsa_adsp_libFastRPC_UTF_Forward_Qtc2_skel_so \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_skel_so \
    vendor_lib_rfsa_adsp_libscveBlobDescriptor_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    com.qualcomm.qti.ant@1.0 \
    com.qualcomm.qti.bluetooth_audio@1.0 \
    com.qualcomm.qti.dpm.api@1.0 \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.quicinc.cne.api@1.0 \
    com.quicinc.cne.api@1.1 \
    com.quicinc.cne.constants@1.0 \
    com.quicinc.cne.constants@2.0 \
    com.quicinc.cne.constants@2.1 \
    lib-imscamera \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmframework \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.config@1.0 \
    vendor.display.config@1.1 \
    vendor.display.config@1.10 \
    vendor.display.config@1.11 \
    vendor.display.config@1.12 \
    vendor.display.config@1.2 \
    vendor.display.config@1.3 \
    vendor.display.config@1.4 \
    vendor.display.config@1.5 \
    vendor.display.config@1.6 \
    vendor.display.config@1.7 \
    vendor.display.config@1.8 \
    vendor.display.config@1.9 \
    vendor.display.postproc@1.0 \
    vendor.qti.data.factory@1.0 \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.bluetooth_audio@2.0 \
    vendor.qti.hardware.btconfigstore@1.0 \
    vendor.qti.hardware.camera.device@1.0 \
    vendor.qti.hardware.capabilityconfigstore@1.0 \
    vendor.qti.hardware.cvp@1.0-adapter-helper \
    vendor.qti.hardware.cvp@1.0 \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.factory@1.0 \
    vendor.qti.hardware.factory@1.1 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.iop@1.0 \
    vendor.qti.hardware.iop@2.0 \
    vendor.qti.hardware.perf@1.0 \
    vendor.qti.hardware.perf@2.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.scve.objecttracker@1.0-adapter-helper \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0-adapter-helper \
    vendor.qti.hardware.scve.panorama@1.0 \
    vendor.qti.hardware.seccam@1.0 \
    vendor.qti.hardware.sensorscalibrate@1.0 \
    vendor.qti.hardware.sigma_miracast@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.wigig.netperftuner@1.0 \
    vendor.qti.hardware.wigig.supptunnel@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.imsrtpservice@2.0 \
    vendor.qti.imsrtpservice@2.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.voiceprint@1.0 \
    vendor.qti.hardware.wifi.keystore@1.0 \
    WfdService \
    CACertService \
    CneApp \
    ConnectionSecurityService \
    IWlanService \
    LenovoRUStub \
    SSGTelemetryService \
    TimeService \
    TrustZoneAccessService \
    PowerOffAlarm \
    QtiTelephonyService \
    ims \
    qcrilmsgtunnel \
    android.hardware.atrace@1.0-service.xml \
    android.hardware.cas@1.1-service.xml \
    android.hardware.gnss@2.0-service-qti.xml \
    vendor.qti.gnss@3.0-service.xml \
    wfdservice \
    ATFWD-daemon \
    KmInstallKeybox \
    PktRspTest \
    SoterProvisioningTool \
    adpl \
    adsprpcd \
    athdiag \
    audioflacapp \
    bc \
    btconfig \
    cdsprpcd \
    cnd \
    cnss-daemon \
    cnss_cli \
    cnss_diag \
    cplay \
    diag_callback_sample \
    diag_dci_sample \
    diag_klog \
    diag_mdlog \
    diag_socket_log \
    diag_uart_log \
    dpmQmiMgr \
    dumpsys \
    e_loop \
    fingerprint \
    fm_qsoc_patches \
    fmconfig \
    fmfactorytest \
    fmfactorytestserver \
    fstman \
    ftmdaemon \
    ftmtest \
    garden_app \
    hal_proxy_daemon \
    hbtp_daemon \
    hostapd_cli \
    hvdcp_opti \
    android.hardware.atrace@1.0-service \
    android.hardware.audio@2.0-service \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.camera.provider@2.4-service \
    android.hardware.cas@1.1-service \
    android.hardware.configstore@1.1-service \
    android.hardware.drm@1.0-service \
    android.hardware.drm@1.2-service.clearkey \
    android.hardware.drm@1.2-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gnss@2.0-service-qti \
    android.hardware.graphics.allocator@2.0-service \
    android.hardware.graphics.composer@2.1-service \
    android.hardware.health@2.0-service \
    android.hardware.keymaster@3.0-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    android.hardware.light@2.0-service \
    android.hardware.media.omx@1.0-service \
    android.hardware.memtrack@1.0-service \
    android.hardware.power@1.0-service \
    android.hardware.sensors@1.0-service \
    android.hardware.thermal@1.0-service \
    android.hardware.vibrator@1.0-service \
    android.hardware.wifi@1.0-service \
    capabilityconfigstoretest \
    hostapd \
    qcrild \
    rild \
    vendor.display.color@1.0-service \
    vendor.dolby.hardware.dms@1.0-service \
    vendor.qti.esepowermanager@1.0-service \
    vendor.qti.hardware.acc_calibrate@1.0-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.cryptfshw@1.0-service-qti \
    vendor.qti.hardware.factory@1.0-service \
    vendor.qti.hardware.perf@2.0-service \
    vendor.qti.hardware.qdutils_disp@1.0-service-qti \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    wpa_supplicant \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    ipacm \
    ipacm-diag \
    irsc_util \
    iwpriv \
    loc_launcher \
    loopbacktest \
    lowi-server \
    mlid \
    mm-audio-ftm \
    mm-pp-dpps \
    mm-qcamera-app \
    mm-qjpeg-dec-test \
    mm-qjpeg-enc-test \
    mm-qomx-idec-test \
    mm-qomx-ienc-test \
    mmid \
    msm_irqbalance \
    netmgrd \
    oemowninfo \
    pktlogconf \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    ptt_socket_app \
    qdmastatsd \
    qjpeg-dma-test \
    qmi_test_mt_client_init_instance \
    qmi_simple_ril_test \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecom_sample_client \
    qseecomd \
    qti \
    rmt_storage \
    secure_ui_sample_client \
    sensors.qti \
    sigma_dut \
    slim_daemon \
    spectraltool \
    ssgqmigd \
    ssgtzd \
    ssr_diag \
    ssr_setup \
    subsystem_ramdump \
    tbaseLoader \
    test_diag \
    test_module_pproc \
    tftp_server \
    thermal-engine \
    time_daemon \
    vendor.qti.hardware.soter@1.0-provision \
    vendor_cmd_tool \
    vm_bms \
    wcnss_service \
    wdsdaemon \
    wifidisplayhalservice \
    wigighalsvc \
    wigignpt \
    wpa_cli \
    xtra-daemon \
    xtwifi-client \
    xtwifi-inet-agent \
    dpmd
